### ISSUE TITLE
[Mac] Remove dependancy on Homebrew

### ISSUE THREAD

**Issue by erichelgeson** [erichelgeson/BlueSCSI-Updater#1]
Currently homebrew allows us to install openocd and dfu-util and avoid notarization errors. While it works, it's a pain for end users who will only use it for this one task. 

- Can we compile & sign openocd & dfu-util ourselves and include it in the download?
- Are there other options?

**Comment by ajacocks** [comment]
The other option is to include non-signed binaries, and instruct users to right-click and select "open" to execute.
This will only work on Macs with the appropriate settings, though.

**Comment by gingerbeardman** [comment]
Yes please.

I had to install brew, do the update and then uninstall brew (thankfully they have an official uninstall script).

**Comment by gingerbeardman** [comment]
Yes please.

If I was to use brew I 'd have to install it, do the update (which takes an eternity on my old Mojave laptop because brew no longer hosts pre-built packages so everything gets built from source!!! Yes, in 2023) and then uninstall brew (thankfully they have an official uninstall script). I abandoned the process after 15 minutes.

Mac Ports was a better option for me because they still provide Mojave pre-built packages. As you'd expect from a package manager. Whole process took less than a minute.

Either way, if the user does not have anything it would be cool if the script took care of things.

**Comment by erichelgeson** [comment]
I think the solution will be to use [QMK Toolbox ](https://github.com/qmk/qmk_toolbox) going forward - it's cross platform and just works. Due to code singing requirements and me not being a desktop developer - this seems like the most senseable path forward.

**Comment by gingerbeardman** [comment]
FWIW, QMK Toolbox will not run on Mojave. It requires Catalina and above.

I do have a more modern Mac, just not to hand right now.

**Comment by erichelgeson** [comment]
Mojave is end of life - which brings another point of why I'd not like to support desktop apps :)

**Comment by gingerbeardman** [comment]
End of life? 🤔 

We're here discussing SCSI solutions for vintage Macs!
